version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: aria_keren2727
      POSTGRES_PASSWORD: obstraawdj29hi_DBS_k2e92wj
      POSTGRES_DB: products_db
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
